apply plugin: 'com.android.application'

android {
    compileSdkVersion 30

    signingConfigs {
        sigin {
            if (file("BUNNY.jks").exists()) {
                storeFile file("BUNNY.jks")
                storePassword "000624"
                keyAlias "bunny"
                keyPassword "426000"
            }
        }
    }

    defaultConfig {
        applicationId 'tv.org.eu.bunnyabc'
        minSdkVersion 16
        //noinspection ExpiredTargetSdkVersion
        targetSdkVersion 26
        versionCode 12
        versionName '0.0.0'
        multiDexEnabled true

        // 锁定 x86 与 armeabi-v7a 架构，保证 x86 平板优先加载原生 x86 动库并减小体积
        ndk {
            abiFilters 'x86', 'armeabi-v7a'
        }

        // 设置 room 的 Schema 位置
        javaCompileOptions {
            annotationProcessorOptions {
                arguments = ["room.schemaLocation": "$projectDir/schemas".toString()]
            }
        }

        if (file("BUNNY.jks").exists()) {
            signingConfig signingConfigs.sigin
        }
    }

    applicationVariants.all { variant ->
        variant.outputs.all { output ->
            if (variant.buildType.name.equals('release')) {
                def releaseApkName = "Jade_SHJ_${releaseTime()}_${variant.buildType.name}.apk"
                output.getPackageApplication().outputDirectory = new File(project.rootDir.absolutePath + "/Release")
                output.outputFileName = releaseApkName
            }
        }
    }

    packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
        // 防止多个 C++ 依赖库合并时 libc++_shared.so 冲突
        pickFirst 'lib/x86/libc++_shared.so'
        pickFirst 'lib/armeabi-v7a/libc++_shared.so'
    }

    buildTypes {
        debug {
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            minifyEnabled false
        }
        release {
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            minifyEnabled true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }

    // 针对 Android 4.x (Dalvik) 虚拟机的线性内存限制深度优化
    dexOptions {
        javaMaxHeapSize "4g"
        additionalParameters += '--multi-dex'
        additionalParameters += '--set-max-idx-number=48000'
        additionalParameters += '--minimal-main-dex'
    }
}

def releaseTime() {
    return new Date().format("yyyyMMddHHmm", TimeZone.getTimeZone("GMT+08:00"))
}

dependencies {
    api fileTree(dir: "libs", include: ["*.jar"])

    implementation 'org.nanohttpd:nanohttpd:2.3.1'
    implementation 'com.google.zxing:core:3.4.1'
    implementation 'androidx.appcompat:appcompat:1.3.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    implementation 'androidx.lifecycle:lifecycle-extensions:2.2.0'
    implementation 'androidx.recyclerview:recyclerview:1.2.1'
    implementation files('libs/thunder.jar')
    implementation files('libs/commons-lang3-3.12.0.jar')
    implementation files('libs/xupdate-lib-release.aar')

    implementation 'com.squareup.okhttp3:okhttp:3.12.11'
    annotationProcessor 'androidx.room:room-compiler:2.3.0'
    implementation 'androidx.room:room-runtime:2.3.0'
    implementation 'androidx.multidex:multidex:2.0.1'
    implementation 'com.squareup.okio:okio:2.8.0'
    implementation 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.45-androidx'
    implementation 'com.kingja.loadsir:loadsir:1.3.8'
    implementation 'com.google.code.gson:gson:2.8.7'
    implementation 'com.squareup.picasso:picasso:2.71828'
    implementation 'me.jessyan:autosize:1.2.1'
    implementation('com.thoughtworks.xstream:xstream:1.4.15') {
        exclude group: 'xmlpull', module: 'xmlpull'
    }
    implementation 'org.greenrobot:eventbus:3.2.0'
    implementation 'com.orhanobut:hawk:2.0.1'

    implementation project(":player")
    implementation project(":quickjs")

    implementation('org.xwalk:xwalk_shared_library:23.53.589.4') {
        exclude group: 'com.android.support'
    }
    implementation 'com.lzy.net:okgo:3.0.4'
    implementation 'com.owen:tv-recyclerview:3.0.0'

    implementation 'com.github.getActivity:XXPermissions:13.6'
    implementation 'org.jsoup:jsoup:1.14.1'
    implementation 'com.github.hedzr:android-file-chooser:v1.2.0-final'
    implementation 'commons-io:commons-io:2.11.0'
    implementation 'com.googlecode.juniversalchardet:juniversalchardet:1.0.3'
}
